### ISSUE TITLE
Add snippets to yassnippet

### ISSUE THREAD

**Issue by ghost** [KusoIDE/KusoIDE#11]
In order to snippets of  yassnippet added to emacs you need to recursively clone yassnippets repo.
See: https://github.com/capitaomorte/yasnippet

**Comment by lxsameer** [comment]
According to https://github.com/capitaomorte/yasnippet#install-with-el-get and our `yasnippet` recipe in `el-get` repository. we shouldn't have any problem. Also I re-install it couple of times and I didn't see any problem. 

But can you provide me a failing scenario ?

**Comment by lxsameer** [comment]
Fixed in rc2
