### ISSUE TITLE
Add God Mode to KusoIDE

### ISSUE THREAD

**Issue by ghost** [KusoIDE/KusoIDE#6]
God Mode is a very nice and powerful mode for emacs:
This is a global minor mode for entering Emacs commands without modifier keys.
see how it works at https://github.com/chrisdone/god-mode
also this useful:

```
;; bind Caps-Lock to god-local-mode
;; http://sachachua.com/wp/2008/08/04/emacs-caps-lock-as-m-x/
;; of course, this disables normal Caps-Lock for *all* apps...
(if (eq window-system 'x)
    (shell-command "xmodmap -e 'clear Lock' -e 'keycode 66 = F13'"))
(global-set-key [f13] 'god-local-mode)
```

**Comment by lxsameer** [comment]
Just install it using `el-get-install` and configure your key binding in `~/.kuso`

BTW thanks for participating
